// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIgfGmIgOvKSHB7ZURJFNrErepTpqqhCA',
    appId: '1:823737478573:web:85dd0830206542e182c524',
    messagingSenderId: '823737478573',
    projectId: 'chat-app-2f6a1',
    authDomain: 'chat-app-2f6a1.firebaseapp.com',
    storageBucket: 'chat-app-2f6a1.appspot.com',
    measurementId: 'G-HYFH7E71YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcUugcvFttZ8R2qs4hrGBwJwlOpSczjyY',
    appId: '1:823737478573:android:50122277d7e822c782c524',
    messagingSenderId: '823737478573',
    projectId: 'chat-app-2f6a1',
    storageBucket: 'chat-app-2f6a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcuJsHYXMSS6C-5SHVUUdrapOVkVLye1U',
    appId: '1:823737478573:ios:f52648b9a05db7d682c524',
    messagingSenderId: '823737478573',
    projectId: 'chat-app-2f6a1',
    storageBucket: 'chat-app-2f6a1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcuJsHYXMSS6C-5SHVUUdrapOVkVLye1U',
    appId: '1:823737478573:ios:2efd340500bda72d82c524',
    messagingSenderId: '823737478573',
    projectId: 'chat-app-2f6a1',
    storageBucket: 'chat-app-2f6a1.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
